import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar flex justify-between bg-neutral text-primary-content shadow-xl">
          <button className="btn btn-ghost text-2xl text-white">Pokeverse</button>
          <div className="flex gap-4"> 
            <div className="form-control">
              <input type="text" placeholder="Search" className="input text-white input-bordered w-24 md:w-auto" />
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
